# -*- coding: utf-8 -*-
"""Scraping1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSQVkbE-G0LqxWUkJq5WUePtQgZagvLM
"""

pip install html-table-parser-python3

pip install bs4

import urllib.request
from html_table_parser import HTMLTableParser
import pandas as pd
from bs4 import BeautifulSoup
import requests
import numpy as np

df_pop=pd.read_csv('Provincial_Summaries.csv')
url='https://www150.statcan.gc.ca/n1/pub/11-402-x/2010000/chap/geo/tbl/tbl07-eng.htm'
req = urllib.request.Request(url=url)
f = urllib.request.urlopen(req)
page=f.read()  
html=page.decode('utf-8')
p = HTMLTableParser()
p.feed(html)
area={}
for i in range(2,16):
    area[p.tables[0][i][0]]=p.tables[0][i][3]

#url="https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec#c63035"
url='https://www.gov.mb.ca/covid19/updates/cases.html'
html_content = requests.get(url).text

soup = BeautifulSoup(html_content, "lxml")
print(soup.prettify())

gdp_table = soup.find("table")

gdp_table

#url="https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec#c63035"
url='https://www.canada.ca/en/public-health/services/publications/diseases-conditions/asthma-chronic-obstructive-pulmonary-disease-canada-2018.html'
html_content = requests.get(url).text

soup = BeautifulSoup(html_content, "lxml")
print(soup.prettify())

gdp_table = soup.find("table")

gdp_table

url='https://www150.statcan.gc.ca/t1/tbl1/en/cv!recreate.action?pid=2410000201&selectedNodeIds=1D22,1D56,1D105,1D112&checkedLevels=0D1,1D1,2D1,3D1&refPeriods=20200101,20210201&dimensionLayouts=layout3,layout2,layout2,layout2,layout2&vectorDisplay=false'
req = urllib.request.Request(url=url)
f = urllib.request.urlopen(req)
page=f.read()  
html=page.decode('utf-8')
p = HTMLTableParser()
p.feed(html)

a=[]
p.tables[0][5][1:15]

url='https://www150.statcan.gc.ca/t1/tbl1/en/cv!recreate.action?pid=2410000301&selectedNodeIds=1D6,1D7,1D10,1D11&checkedLevels=0D1,1D1&refPeriods=20200101,20210401&dimensionLayouts=layout3,layout2,layout2&vectorDisplay=false'
req = urllib.request.Request(url=url)
f = urllib.request.urlopen(req)
page=f.read()  
html=page.decode('utf-8')
q = HTMLTableParser()
q.feed(html)

q.tables[0][3][1:15]

li=['ca','qb','on','ab','bc','ca-us','qb-us','on-us','ab-us','bc-us']
df=pd.DataFrame(columns=li)

i=5;j=3
for c in li[:5]:
  df[c]=q.tables[0][j][1:15]
  j=j+1
for c in li[5:]:
  df[c]=p.tables[0][i][1:15]
  i=i+1

df.to_csv('/content/drive/MyDrive/ML project/travel.csv')

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""